{
 "title": "Netgear Plus Exporter Full",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(netgear_plus_up{job=\"netgear_plus\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Host:",
    "query": {
     "query": "label_values(netgear_plus_up{job=\"$job\"},instance)"
    }
   },
   {
    "name": "switchfirmware",
    "label": "switchfirmware",
    "query": {
     "query": "label_values(netgear_plus_switch_info{job=\"$job\", instance=\"$instance\"},firmware)"
    }
   },
   {
    "name": "switchserialnumber",
    "label": "switchserialnumber",
    "query": {
     "query": "label_values(netgear_plus_switch_info{job=\"$job\", instance=\"$instance\"},serial_number)"
    }
   },
   {
    "name": "switchname",
    "label": "switchname",
    "query": {
     "query": "label_values(netgear_plus_switch_info{job=\"$job\", instance=\"$instance\"},name)"
    }
   },
   {
    "name": "switchbootloader",
    "label": "switchbooatloader",
    "query": {
     "query": "label_values(netgear_plus_switch_info{job=\"$job\", instance=\"$instance\"},bootloader)"
    }
   },
   {
    "name": "switchmodel",
    "label": "switchmodel",
    "query": {
     "query": "label_values(netgear_plus_switch_info{job=\"$job\", instance=\"$instance\"},model)"
    }
   },
   {
    "name": "switchhostname",
    "label": "switchhostname",
    "query": {
     "query": "label_values(netgear_plus_switch_info{job=\"$job\", instance=\"$instance\"},ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Info - ${switchname}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "| info | data |\n| --- | --- |\n| model | ${switchmodel} |\n| serial number | ${switchserialnumber} |\n| firmware | ${switchfirmware} |\n| bootloader | ${switchbootloader} |\n| ip/hostname | ${switchhostname} |"
   }
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(netgear_plus_port_receive_bytes_total{instance=\"$instance\",job=\"$job\"}[5m])*8.192",
     "legendFormat": "Port {{port}} rx"
    },
    {
     "expr": "irate(netgear_plus_port_transmit_bytes_total{instance=\"$instance\",job=\"$job\"}[5m])*8.192",
     "legendFormat": "Port {{port}} tx"
    }
   ]
  },
  {
   "title": "Network Traffic CRC Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "irate(netgear_plus_port_crc_errors_total{instance=\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "Port {{port}} - CRC errors"
    }
   ]
  },
  {
   "title": "POE",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "netgear_plus_port_poe_power_watts{instance=\"$instance\",job=\"$job\"} > 0",
     "legendFormat": "Port {{port}}"
    }
   ]
  },
  {
   "title": "Exporter Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "netgear_plus_probe_duration_seconds{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "{{instance}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "netgear_plus_up{job=\"$job\",instance=\"$instance\"}",
       "legendFormat": "{{instance}} - Scrape success"
      }
     ]
    }
   ]
  }
 ]
}